package aspm.architecture;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;

import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import com.tngtech.archunit.core.importer.ImportOption;
import com.tngtech.archunit.library.dependencies.SlicesRuleDefinition;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * CON-PLT-013, CON-PLT-015 and CON-PLT-016 on compiled bytecode.
 *
 * <p>The primary enforcement of CON-PLT-013 is the Gradle subproject partition: another
 * module's domain type is not on the compile classpath, so the violation is a resolution
 * failure with no severity dial and no suppression annotation. These tests are the
 * backstop for the routes the partition cannot see — reflection, generated bytecode, and
 * a type that reaches a foreign internal package through a widened contract.
 */
class ModuleBoundaryTest {

    private static JavaClasses platform;

    @BeforeAll
    static void importPlatform() {
        platform = new ClassFileImporter()
                .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_TESTS)
                .importPackages("aspm..");
    }

    // The two package-pattern rules that previously stood here for CON-PLT-013, CON-PLT-015 and
    // CON-PLT-011 were removed after the prompt 2 deliberate-violation run showed them passing
    // while a violation was present: `resideOutsideOfPackage("aspm.module.(*).domain..")` treats
    // `(*)` as a plain wildcard, so the that() clause excluded every module's domain package.
    // CrossModuleAccessTest replaces them with a source-module-to-target-module comparison.

    @Test
    @DisplayName("CON-PLT-016: the module slice graph is free of cycles")
    void moduleGraphIsAcyclic() {
        SlicesRuleDefinition.slices()
                .matching("aspm.module.(*)..")
                .should().beFreeOfCycles()
                .because("CON-PLT-016: a cycle means the two modules are one module, and it makes "
                        + "extraction impossible without breaking both.")
                .check(platform);
    }

    @Test
    @DisplayName("CON-PLT-016: the kernel slice graph is free of cycles")
    void kernelGraphIsAcyclic() {
        SlicesRuleDefinition.slices()
                .matching("aspm.kernel.(*)..")
                .should().beFreeOfCycles()
                .because("CON-PLT-016 applied to the kernel, where a cycle would be worse: every "
                        + "module depends on all five.")
                .check(platform);
    }

    @Test
    @DisplayName("AI assistance holds no compile-time dependency on any domain module (PRD-AIC-021)")
    void aiAssistanceHasNoDomainDependency() {
        noClasses()
                .that().resideInAPackage("aspm.module.aiassistance..")
                .should().dependOnClassesThat()
                .resideInAnyPackage("aspm.module.assetinventory..", "aspm.module.vulnerabilitymanagement..",
                        "aspm.module.riskprioritization..", "aspm.module.assessment..",
                        "aspm.module.workmanagement..", "aspm.module.organizationscope..",
                        "aspm.module.compositionanalysis..", "aspm.module.capacity..",
                        "aspm.module.ingestion..", "aspm.module.knowledge..")
                .because("PRD-AIC-021 and ADR-005: a behavioural rule is violated by a prompt; an "
                        + "absent dependency is not. Modelled as Separate Ways in DOC-03 section 5.3.")
                .check(platform);
    }
}
